[[redirects]]
  from = "https://dinohacks.acecoding.org/*"
  to = "https://dino-hacks.devpost.com"
  status = 301
  force = true

[[redirects]]
  from = "https://discord.acecoding.org/*"
  to = "https://discord.com/invite/JXPVNxBEnS"
  status = 301
  force = true

[[redirects]]
  from = "https://teach.acecoding.org/*"
  to = "https://forms.gle/NRNJpJjztaA6MjJj8"
  status = 301
  force = true

[[redirects]]
  from = "https://hpms.acecoding.org/"
  to = "https://forms.gle/afvec9vwVM5nhKx87"
  status = 301
  force = true

[[redirects]]
  from = "https://pms.acecoding.org/"
  to = "https://forms.gle/aPux1J8iHUtirP5y7"
  status = 301
  force = true

[[redirects]]
  from = "https://hms.acecoding.org/"
  to = "https://forms.gle/U6iXeQN2k6FwAKyJ8"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.acecoding.org/*"
  to = "https://acecoding.herokuapp.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://join.acecoding.org/*"
  to = "https://forms.gle/q3nCzcm6aRgjnXbQA"
  status = 301
  force = true
