[[redirects]]
  from = "https://dinohacks.acecoding.org/*"
  to = "https://dino-hacks.devpost.com"
  status = 301
  force = true

[[redirects]]
  from = "https://discord.acecoding.org/*"
  to = "https://discord.gg/9f2kHpRNNz"
  status = 301
  force = true

[[redirects]]
  from = "https://teach.acecoding.org/*"
  to = "https://forms.gle/cCVjo3qnMpNgapdTA"
  status = 301
  force = true

[[redirects]]
  from = "https://hpms.acecoding.org/"
  to = "https://forms.gle/ndzTE5T3JVvFpJKF8"
  status = 301
  force = true

[[redirects]]
  from = "https://pms.acecoding.org/"
  to = "https://forms.gle/F7jt3BAMTWW3JXUR9"
  status = 301
  force = true

[[redirects]]
  from = "https://hms.acecoding.org/"
  to = "https://forms.gle/aizXrpUkYbdHjBty5"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.acecoding.org/*"
  to = "https://acecoding.herokuapp.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://join.acecoding.org/*"
  to = "https://forms.gle/mYaT3u4JXxAZ5SNn7"
  status = 301
  force = true
